"""Default configuration values."""

DEFAULT_CONVENTION_NAME = "oriented_core_bottom_ref"
DEFAULT_OUTPUT_FILE = "computed_orientations.csv"

STEREONET_PROJECTION_EQUAL_AREA = "equal-area"
STEREONET_PROJECTION_EQUAL_ANGLE = "equal-angle"
SUPPORTED_STEREONET_PROJECTIONS = (
    STEREONET_PROJECTION_EQUAL_AREA,
    STEREONET_PROJECTION_EQUAL_ANGLE,
)
DEFAULT_STEREONET_PROJECTION = STEREONET_PROJECTION_EQUAL_AREA
DEFAULT_STEREONET_POLAR_GRID = False

